name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    env:
      METRICS_TOKEN: ${{ secrets.METRICS_TOKEN != '' && secrets.METRICS_TOKEN || secrets.GITHUB_TOKEN }}
      METRICS_TOKEN_SOURCE: ${{ secrets.METRICS_TOKEN != '' && 'METRICS_TOKEN' || 'GITHUB_TOKEN' }}
    steps:
      - name: Log metrics token source
        run: echo "Using $METRICS_TOKEN_SOURCE for metrics generation."
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ env.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.classic.svg
          token: ${{ env.METRICS_TOKEN }}
          base: header, repositories
